platform :ios, '10.0'

target 'TravelUI-Example' do
  use_frameworks!

  pod 'TravelUI', :path => '../'

  target 'TravelUI-ExampleTests' do
    inherit! :search_paths
    
    pod 'TravelUI', :path => '../'
    # Pods for testing
  end

  target 'TravelUI-ExampleUITests' do
    inherit! :search_paths
    
    pod 'TravelUI', :path => '../'
    # Pods for testing
  end

end
